[package]
name = "make_vg_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
polodb_core = "4.4.0"
reqwest = { version = "0.11.24", features = ["blocking"]}
